exports.lang_names =
  '1c':           '1C'
  'actionscript': 'ActionScript'
  'apache':       'Apache'
  'avrasm':       'AVR_Assembler'
  'axapta':       'axapta'
  'bash':         'Bash'
  'befunge':      'Befunge'
  'cmake':        'CMake'
  'coffeescript': 'CoffeeScript'
  'cpp':          'C++'
  'cs':           'C#'
  'css':          'CSS'
  'delphi':       'Delphi'
  'diff':         'Diff'
  'django':       'Django'
  'd':            'D'
  'dos':          'DOS'
  'erlang':       'Erlang'
  'erlang-repl':  'Erlang REPL'
  'glsl':         'GLSL'
  'go':           'Go'
  'haskell':      'Haskell'
  'http':         'HTTP'
  'ini':          'Ini'
  'java':         'Java'
  'javascript':   'JavaScript'
  'json':         'JSON'
  'lisp':         'Lisp'
  'lua':          'Lua'
  'markdown':     'Markdown'
  'matlab':       'Matlab'
  'mel':          'MEL'
  'nginx':        'Nginx'
  'objectivec':   'Objective C'
  'parser3':      'Parser3'
  'perl':         'Perl'
  'php':          'PHP'
  'profile':      'Python profile'
  'python':       'Python'
  'rib':          'RenderMan RIB'
  'r':            'R'
  'rsl':          'RenderMan RSL'
  'ruby':         'Ruby'
  'rust':         'Rust'
  'scala':        'Scala'
  'smalltalk':    'Smalltalk'
  'sql':          'SQL'
  'tex':          'TeX'
  'vala':         'Vala'
  'vbscript':     'VBScript'
  'vhdl':         'VHDL'
  'xml':          'XML'